[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/app"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200
  force = true

[[redirects]]
  from = "/downloads/SwiftTyping-Setup.zip"
  to = "https://github.com/SW-YONTO/SWIFT-TYPING/releases/download/v3.26.7/swit-typingv3.26.7.zip"
  status = 302
  force = true

[[redirects]]
  from = "/downloads/swit-typingv3.26.7.zip"
  to = "https://github.com/SW-YONTO/SWIFT-TYPING/releases/download/v3.26.7/swit-typingv3.26.7.zip"
  status = 302
  force = true
